flags: {}
packages:
- '.'
- deps/elf
- deps/flexdis86
- deps/parameterized-utils
- deps/linux-ptrace
- deps/posix-waitpid
- deps/mss/crucible
- deps/mss/galois-matlab
extra-deps:
- bv-0.3.0
- happy-1.19.5
- io-streams-1.3.1.0
- llvm-pretty-0.3.1.1
resolver: lts-2.16
