flags: {}
packages:
- '.'
- deps/crucible
- deps/dwarf-tools
- deps/elf-edit
- deps/flexdis86
- deps/galois-dwarf
- deps/linux-ptrace
- deps/llvm-pretty
- deps/macaw
- deps/matlab-data
- deps/parameterized-utils
- deps/posix-waitpid
- deps/reopt-crucible
extra-deps:
- bimap-0.3.1
- bv-0.4.0
resolver: lts-6.22