flags: {}
packages:
- '.'
- deps/elf
- deps/flexdis86
- deps/parameterized-utils
- deps/linux-ptrace
- deps/posix-waitpid
- deps/mss/crucible
- deps/mss/galois-matlab
- deps/llvm-pretty
extra-deps:
- bv-0.3.0
resolver: lts-3.3
