flags: {}
packages:
- '.'
- deps/crucible
- deps/dwarf-tools
- deps/elf-edit
- deps/flexdis86
- deps/galois-dwarf
- deps/linux-ptrace
- deps/llvm-pretty
- deps/macaw
- deps/mss/matlab-data
- deps/parameterized-utils
- deps/posix-waitpid
- deps/reopt-crucible
extra-deps:
- bimap-0.3.1
- bv-0.4.0
# Add containers and updated versions of lens and kan-extensions to support macaw
- containers-0.5.8.1
- lens-4.15.1
- kan-extensions-5.0.1
resolver: lts-6.27