packages:
- .
- tools
- deps/dwarf
- deps/elf-edit
- deps/flexdis86
- deps/flexdis86/binary-symbols
- deps/llvm-pretty
- deps/macaw/base
- deps/macaw/x86
- deps/parameterized-utils
extra-deps:
- located-base-0.1.1.1
- monadLib-3.7.3
#- panic-0.4.0.1
#- regex-1.0.1.3
#- s-cargot-0.1.4.0
#- s-cargot-letbind-0.2.2.0
#- tasty-hunit-0.10.0.1
resolver: lts-13.6
# allow-newer: true

# nix:
#  enable: true
#  packages: [glpk, pcre, zlib]