flags: {}
packages:
- '.'
- deps/elf-edit
- deps/flexdis86
- deps/dwarf
- deps/linux-ptrace
- deps/llvm-pretty
- deps/macaw
- deps/macaw-x86
- deps/mss/crucible
- deps/mss/matlab-data
- deps/parameterized-utils
- deps/posix-waitpid
- deps/reopt-crucible
extra-deps:
# Add containers and updated versions of lens and kan-extensions to support macaw
- containers-0.5.8.2
- located-base-0.1.1.0
- th-abstraction-0.1.0.0
resolver: lts-8.13